SOURCES  += i2c_ipass.cpp
HEADERS  += i2c_ipass.hpp

HEADERS  += registers.hpp
SOURCES  += ADXL345.cpp
HEADERS  += ADXL345.hpp

SOURCES  += tests.cpp
HEADERS  += tests.hpp

HEADERS  += line.hpp
HEADERS  += cube.hpp
HEADERS  += moving_cube.hpp
HEADERS  += player.hpp

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
