#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := MPU6050.cpp ChipI2C.cpp WS2801.cpp DisplayController.cpp LedstripController.cpp

# header files in this project
HEADERS := MPU6050.hpp ChipI2C.hpp WS2801.hpp DisplayController.hpp LedstripController.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
