SOURCES  += spi.cpp
HEADERS  += spi.hpp

SOURCES  += matrixLib.cpp
HEADERS  += matrixLib.hpp

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
