SOURCES  += mpu6050.cpp
HEADERS  += mpu6050.hpp

HEADERS  += block.hpp
HEADERS  += brick.hpp
HEADERS  += coin.hpp
HEADERS  += drawable.hpp
HEADERS  += dummy.hpp
HEADERS  += entity.hpp
HEADERS  += flagpole.hpp
HEADERS  += goomba.hpp
HEADERS  += ground.hpp
HEADERS  += level.hpp
HEADERS  += question_block.hpp

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
