SOURCES  += mpu6050.cpp
HEADERS  += mpu6050.hpp

SOURCES  += maze.cpp
HEADERS  += maze.hpp

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
