SOURCES := spaceinvaders.cpp drawable.cpp rocket.cpp spacealien.cpp spaceship.cpp mpu6050.cpp
HEADERS := spaceinvaders.hpp drawable.hpp rocket.hpp spacealien.hpp spaceship.hpp mpu6050.hpp 
SEARCH :=
RELATIVE := ..
include $(RELATIVE)/Makefile.due